#!/bin/bash
set -e

virsh net-start default
virsh net-autostart default

echo "kernel.unprivileged_userns_clone=1" > /etc/sysctl.d/80-lxc-userns.conf
echo "tom veth virbr0 2" > /etc/lxc/lxc-usernet
echo "you should reboot now."

