#!/bin/bash

# var setup
HOME_DIR='/home/tom'
RC_DIR=$HOME_DIR'/src/rc'

# git setup
git config --global user.name "Tom Barrett"
git config --global user.email "tom@tombarrett.xyz"

# dwm setup
DWM_DIR=$HOME_DIR'/src/dwm'
git clone https://git.suckless.org/dwm $DWM_DIR

patch $DWM_DIR'/dwm.c' $RC_DIR'/dwm/vanitygaps.diff'
patch $DWM_DIR'/dwm.c' $RC_DIR'/dwm/custom.diff'

cp $RC_DIR'/dwm/config.h' $DWM_DIR

make -C $DWM_DIR

# dwmstatus setup
DWMSTS_DIR=$HOME_DIR'/src/dwmstatus'
git clone https://git.suckless.org/dwmstatus $DWMSTS_DIR

patch $DWMSTS_DIR'/dwmstatus.c' $RC_DIR'/dwmstatus/custom.diff'

make -C $DWMSTS_DIR

# xorg setup
cp $RC_DIR'/.xinitrc' $HOME_DIR

# autostart script
cp $RC_DIR'/.autostart' $HOME_DIR

# extras
#vboxmanage setproperty machinefolder /home/tom/vms
