#!/bin/bash

# var setup
RC_DIR=$HOME'/src/rc'

# git setup
git config --global user.name "Tom Barrett"
git config --global user.email "tom@tombarrett.xyz"

# bin directory
mkdir $HOME/bin

# dwm setup
DWM_DIR=$HOME'/src/dwm'
git clone https://git.suckless.org/dwm $DWM_DIR

patch $DWM_DIR'/dwm.c' $RC_DIR'/dwm/custom.diff'

ln -s $RC_DIR'/dwm/config.h' $DWM_DIR

make -C $DWM_DIR

ln -s $DWM_DIR/dwm $HOME/bin

# dwmstatus setup
DWMSTS_DIR=$HOME'/src/dwmstatus'
git clone https://git.suckless.org/dwmstatus $DWMSTS_DIR

patch $DWMSTS_DIR'/dwmstatus.c' $RC_DIR'/dwmstatus/custom.diff'

make -C $DWMSTS_DIR

ln -s $DWMSTS_DIR/dwmstatus $HOME/bin

# st setup
ST_DIR=$HOME'/src/st'
git clone https://git.suckless.org/st $ST_DIR

ln -s $RC_DIR'/st/config.h' $ST_DIR

make -C $ST_DIR

ln -s $ST_DIR/st $HOME/bin

# fish setup
ln -s $RC_DIR'/.config/fish' $HOME'/.config'

# freedesktop setup
ln -s $RC_DIR'/.config/user-dirs.dirs' $HOME'/.config'

# xorg setup
ln -s $RC_DIR'/.xinitrc' $HOME

# autostart script
ln -s $RC_DIR'/.autostart' $HOME

# ranger setup
ln -s $RC_DIR'/.config/ranger' $HOME'/.config'

# ncmpcpp setup
ln -s $RC_DIR'/.config/ncmpcpp' $HOME'/.config'

# neomutt setup
ln -s $RC_DIR'/.muttrc' $HOME
ln -s $RC_DIR'/.mailcap' $HOME
