#!/bin/bash

# display
apt install -y \
	xorg \
	xorg-dev \
	xauth \
	nitrogen \
	arandr \
	scrot \
	feh \
	xinit

# utilities
apt install -y \
	htop \
	ncdu \
	tree \
	fish \
	git \
	neovim \
	stterm \
	dmenu

# web
apt install -y \
	w3m \
	w3m-img \
	nmap \
	curl \
	netcat \
	firefox-esr

# security
apt install -y \
	ccrypt \
	pwgen

# lxc containers
apt install -y \
	lxc \
	libvirt0 \
	libpam-cgfs \
	bridge-utils \
	libvirt-clients \
	libvirt-daemon-system \
	iptables \
	ebtables \
	dnsmasq-base

# misc
apt install -y \
	acpi \
	lshw \
	build-essential \
	psmisc
