#!/bin/bash
apt install w3m \
	    firefox-esr \
	    xorg \
	    xorg-dev \
	    nitrogen \
	    arandr \
	    scrot \
	    feh \
	    xinit \
	    htop \
	    ncdu \
	    tree \
    	    fish \
	    git \
	    neovim \
	    stterm \
	    dmenu \
	    acpi \
	    build-essential \
	    psmisc
